{% set name = "rst2pdf" %}
{% set version = "0.99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8fa23fa93bddd1f52d058ceaeab6582c145546d80f2f8a95974f3703bd6c8152

build:
  number: 0
  noarch: python
  entry_points:
    - rst2pdf = rst2pdf.createpdf:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - docutils
    - jinja2
    - pdfrw
    - pygments
    - python
    - reportlab
    - setuptools
    - six
    - smartypants
    - importlib_metadata
    - packaging

test:
  imports:
    - rst2pdf
  commands:
    - rst2pdf --help

about:
  home: https://rst2pdf.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Convert reStructured Text to PDF via ReportLab.
  doc_url: https://rst2pdf.org/static/manual.html
  dev_url: https://github.com/rst2pdf/rst2pdf

extra:
  recipe-maintainers:
    - chrisburr
