{% set name = "rst2pdf" %}
{% set version = "0.101" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rst2pdf-{{ version }}.tar.gz
  sha256: 005f05b2c10814799e636a15ac03cd7bce696e680a58ee76c83eb270d3734d28

build:
  entry_points:
    - rst2pdf = rst2pdf.createpdf:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8
    - docutils
    - importlib-metadata
    - jinja2
    - packaging
    - pygments
    - pyyaml
    - reportlab
    - smartypants

test:
  imports:
    - rst2pdf
  commands:
    - pip check
    - rst2pdf --help
  requires:
    - pip

about:
  home: https://rst2pdf.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Convert reStructured Text to PDF via ReportLab.
  doc_url: https://rst2pdf.org/static/manual.html
  dev_url: https://github.com/rst2pdf/rst2pdf

extra:
  recipe-maintainers:
    - chrisburr
