{% set name = "rst2pdf" %}
{% set version = "0.103.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rst2pdf-{{ version }}.tar.gz
  sha256: 3ffe816d4b3275aee21b8ffdd08b2e6be4d7590cd88b189f733cbc6996d63786

build:
  entry_points:
    - rst2pdf = rst2pdf.createpdf:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - docutils
    - importlib-metadata
    - jinja2
    - packaging
    - pygments
    - pyyaml
    - reportlab
    - smartypants

test:
  imports:
    - rst2pdf
  commands:
    - pip check
    - rst2pdf --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://rst2pdf.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Convert reStructured Text to PDF via ReportLab.
  doc_url: https://rst2pdf.org/static/manual.html
  dev_url: https://github.com/rst2pdf/rst2pdf

extra:
  recipe-maintainers:
    - chrisburr
